### ISSUE TITLE
BOM for the project ?

### ISSUE THREAD

**Issue by pottierjc** [dtheodor79/A600-RGB2HDMI#1]
Hi!

I would like to assemble this nice project however I can't find the component list?

I may very well miss something since I'm a newbie :$

Hope you can help!

Thanks.

**Comment by dtheodor79** [comment]
Hi, the only module required, with respect to the PCB, is a [PLCC 52](https://www.google.com/search?q=PLCC+52&sxsrf=AOaemvIjwsZYK8vsP7v_-x1TQAxiebYXjA:1632723830470&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjcpLmfwp7zAhUMgP0HHdFLAF8Q_AUoAXoECAEQAw&biw=1920&bih=937&dpr=1). Pay attention to mount it correctly; the PLCC module should be at the bottom layer and its pins at the top layer, and its cut must be aligned as shown on the PCB.

Optionally, you can connect a push button to the BT1 and BT2 for accessing the menu.

Of course you will need to buy the RGB2HDMI adapter that is connected to the PCB as shown in the readme.md.

**Comment by pottierjc** [comment]
That's perfect, thank you.

**Comment by dtheodor79** [comment]
You are welcome! Post few pictures when done if you like ;)
